config/routes.rb
Rails.application.routes.draw do
  
  resources :permissions, :comments, :grouptasks, :statistics
  
  match 'logins/user_auth' => 'logins#user_auth', :as => 'user_auth', via: [:get, :post]
  match 'logins/logout' => 'logins#logout', :as => 'logout', via: [:get, :post]
          
  get ':controller/:action/:id'
  get ':controller/:action/:id.:format'
  

  root 'logins#index'

  post 'grouptasks/create_comment/:id'        => 'grouptasks#create_comment'
  post 'grouptasks/create_comment_reply/:id'  => 'grouptasks#create_comment_reply'
  post 'grouptasks/edit_comment/:id'          => 'grouptasks#edit_comment'
  post 'grouptasks/update_comment/:id'        => 'grouptasks#update_comment'
  

end

app/models/comment.rb
class Comment < ActiveRecord::Base  
  acts_as_tree :order => 'created_at'
  has_attached_file :audio, :url => "#{ActionController::Base.relative_url_root}/system/audio/:id/:basename.:extension",
                            :path => ":rails_root/public/system/audio/:id/:basename.:extension"
  validates_attachment_content_type :audio, :content_type => ['audio/mpeg', 
                                                              'audio/x-mpeg', 
                                                              'audio/mp3', 
                                                              'audio/x-mp3', 
                                                              'audio/mpeg3', 
                                                              'audio/x-mpeg3', 
                                                              'audio/mpg', 
                                                              'audio/x-mpg', 
                                                              'audio/x-mpegaudio',
                                                              'video/quicktime',
                                                              'audio/quicktime' ],
                                              :message => 'Not a valid audio file.'
  
  
  belongs_to  :sessionrecording
  belongs_to  :student
  
  # Currently this isn't doing any filtering, but could be used to filter more finitely the comments if needed.
  scope :viewable_by, ->(args) {
    user = args.first
    task = args.last
    includes(:student, :sessionrecording, :usersession, :task)
    case
      when user.is_super_admin? then {}
      when task.instructor == user then {}
      when task.permission && task.permission.discussionable == 'group' then {}
      else {}
    end
    order(created_at: :asc)
  }
      
  def grouptask
    return Grouptask.find(Usersession.find(self.sessionrecording.associatedusersessionid).associatedgrouptaskid)
  end
  
  def sessionrecording
    return Sessionrecording.find(self.sessionrecording_id)
  end
  
  #This isn't used anywhere yet.
  def set_audio_length(file)
    Mp3Info.open(file) do |mp3| 
      self.audio_length = mp3.length
    end
  end
    
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
      
  # GET /comments
  # GET /comments.xml
  def index
    @comments = Comment.find(:all)

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @comments }
    end
  end

  # GET /comments/1
  # GET /comments/1.xml
  def show
    @comment = Comment.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @comment }
    end
  end

  # GET /comments/new
  # GET /comments/new.xml
  def new
    @comment = Comment.new
    if params[:parent]
      @parent = Comment.find(params[:parent])
    end
    @rec = Sessionrecording.find(params[:rec])

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @comment }
    end
  end

  # GET /comments/1/edit
  def edit
    @comment = Comment.find(params[:id])
    if @comment.parent
      @parent = @comment.parent
    end
    @rec = @comment.sessionrecording
  end

  # POST /comments
  # POST /comments.xml
  def create
    @comment = Comment.create(comment_params(params))
    
    respond_to do |format|
      if @comment.save
        flash[:notice] = 'Comment was successfully created.'
        format.html { redirect_to(url_for(:controller => 'grouptasks', :action => 'show', :id => @comment.sessionrecording.task, :show_comments_for => @comment.sessionrecording))}
        format.xml  { render :xml => @comment, :status => :created, :location => @comment }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @comment.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /comments/1
  # PUT /comments/1.xml
  def update
    @comment = Comment.find(params[:id])

    respond_to do |format|
      if @comment.update_attributes(comment_params(params))
        flash[:notice] = 'Comment was successfully updated.'
        format.html { redirect_to(url_for(:controller => 'grouptasks', :action => 'show', :id => @comment.sessionrecording.task, :show_comments_for => @comment.sessionrecording))}
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @comment.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /comments/1
  # DELETE /comments/1.xml
  def destroy
    @comment = Comment.find(params[:id])
    @comment.destroy

    respond_to do |format|
      format.html { redirect_to(comments_url) }
      format.xml  { head :ok }
    end
  end
  
  private
  
  def comment_params(params)
    params.require(:comment).permit(:body, :student_id, :kind, :sessionrecording_id, :parent_id)
  end
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/views/comments/_audioplayer.html.erb
<div class="audioclip">
  <div id="player_wrapper">
  	<span id="qtplayer">
  	</span>
  </div>
	<script language="JavaScript" type="text/javascript"> 
			QT_ReplaceElementContents_XHTML( document.getElementById("qtplayer"),
											 '<%= "#{@rec.url_to_file}" %>', '100%', '16', '',
					 						 'autoplay', 'false',
											 'showlogo', 'false',
					 						 'kioskmode', 'true',
											 'align', 'middle',
											 'EnableJavaScript', 'True',
											 'postdomevents', 'true',
											 'emb#NAME' , '<%= @rec.identifier %>' , 
											 'obj#id' , 'theplayer', 
											 'emb#id', '<%= @rec.identifier %>'
											);
										
			Event.observe(
					window,
					'qt_play',
					function() {
						var timePlay = setInterval(function() { 
														var timedisplay = document.getElementById('player_timecode');
														var player = document.getElementById('<%= @rec.identifier %>');
							
														var currentTime=player.GetTime()/player.GetTimeScale();
														var minutes=Math.floor(currentTime/60);
														var seconds=parseInt(currentTime % 60);
														var timecode=pad(minutes.toString(), 2) + ':' + pad(seconds.toString(), 2);
							
														timedisplay.update(timecode);
													}
													, 500);
					}
				);
			
			Event.observe(window,'qt_pause',function() {var timePlay=window.clearInterval(timePlay);});
			Event.observe(window,'qt_ended',function() {var timePlay=window.clearInterval(timePlay);});
		
			Event.observe( 	window, 
							'qt_timechanged', 
							function() { 
									var timedisplay = document.getElementById('player_timecode');
									var player = document.getElementById('<%= @rec.identifier %>');
								
									var currentTime=player.GetTime()/player.GetTimeScale();
									var minutes=Math.floor(currentTime/60);
									var seconds=parseInt(currentTime % 60);
									var timecode=pad(minutes.toString(), 2) + ':' + pad(seconds.toString(), 2);
								
									timedisplay.update(timecode);
								}
							);
	</script>
	<span class="downloadfile">
  	<% if @rec.downloadable?(current_user) %>
  	  <%= link_to "Download", "#{@rec.url_to_file}" %> (Right-click and choose "Save As...")
  	<% end %>
	</span>
	<span id="player_timecode" class="player_timecode">00:00</span>
</div>

app/views/comments/_newaudioplayer.html.erb
<div id="recording-audioplayer" class="panel callout radius">
	<strong><%= @rec.cliptitle %></strong>
	<a class="play icon" title="Play" href="#"></a>
	<a class="stop icon" title="Stop" href="#"></a>

	<div id="wave"></div>
	<div id="wave-timeline"></div>
	<!-- <p><strong>Spectrogram</strong></p> -->
	<!-- <div id="wave-spectrogram"></div> -->
</div>

<script>

	var wavesurfer = Object.create(WaveSurfer);

	wavesurfer.init({
		container: '#wave',
		waveColor: 'violet',
		progressColor: 'purple',
		height: 75,
		normailize: true
	});

	wavesurfer.load('<%= "#{@rec.url_to_file(ssl: request.ssl?)}" %>');

	wavesurfer.on('ready', function () {
		// wavesurfer.play();

		var timeline = Object.create(WaveSurfer.Timeline);
		
		timeline.init({
		    wavesurfer: wavesurfer,
		    container: "#wave-timeline"
		});

		// var spectrogram = Object.create(WaveSurfer.Spectrogram);
		//
		// spectrogram.init({
		//     wavesurfer: wavesurfer,
		//     container: "#wave-spectrogram"
		// });
		
		$(function() {
			$(document).on('click', '#recording-audioplayer .play', function(){
				$('#recording-audioplayer .play').addClass("pause");
				$('#recording-audioplayer .play').removeClass("play");
			  wavesurfer.play();
			});

			$(document).on('click', '#recording-audioplayer .pause', function(){
				$('#recording-audioplayer .pause').addClass("play");
				$('#recording-audioplayer .pause').removeClass("pause");
			  wavesurfer.playPause();
			});

			$(document).on('click', '#recording-audioplayer .stop', function(){
				$('#recording-audioplayer .pause').addClass("play");
				$('#recording-audioplayer .pause').removeClass("pause");
			  wavesurfer.stop();
			});
		});
	
	});	
</script>

app/views/comments/edit.html.erb
<div id="content">
  <h1>Edit Comment on "<%= @comment.sessionrecording.cliptitle %>"</h1>
  <div class="content_container">
    <div class="standalone_comment_form">
      <%= render :partial => 'audioplayer', :object => @rec %>

      <% form_for @comment, :html => { :multipart => true } do |f| %>
        <%= f.error_messages %>
        <p>
      		<%= f.text_area :body, :rows => 10, :id => 'new_comment' %>
      		<%= f.file_field :audio %>
      		<%= button_to_function 'Insert Current Timecode', "InsertTime(#{@comment.sessionrecording.identifier},new_comment)", :class => "timecode_button" %>
        <p>
          <%= f.submit "Save" %>
        </p>
      <% end %>

      <%= link_to 'Back', @comment.sessionrecording.task %>
    </div>
  </div>
</div>

app/views/comments/index.html.erb
<h1>Listing comments</h1>

<table>
  <tr>
  </tr>

<% for comment in @comments %>
  <tr>
    <td><%= link_to 'Show', comment %></td>
    <td><%= link_to 'Edit', edit_comment_path(comment) %></td>
    <td><%= link_to 'Destroy', comment, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New comment', new_comment_path %>

app/views/comments/new.html.erb
<div id="content">
  <h1>New Comment on "<%= @rec.cliptitle %>"</h1>
  <div class="content_container">
    <div class="standalone_comment_form">
      <%= render :partial => 'newaudioplayer', :object => @rec %>

      <%= form_for @comment, :html => { :multipart => true } do |f| %>
        <%= f.error_messages %>
        <p>
      		<%= f.text_area :body, :rows => 10, :id => 'new_comment' %>
      		<% if @parent %>
      		  <%= hidden_field_tag 'comment[parent_id]', @parent.id %>
      		<% end %>
      		<%= hidden_field_tag 'comment[student_id]', current_user.id %>
      		<%= hidden_field_tag 'comment[sessionrecording_id]', @rec.id %>
      		<%= hidden_field_tag 'comment[kind]', comment_kind(@rec.task) %><br/>
      		<%= f.file_field :audio %>
		<a class="timecode button secondary" href="javascript:void(0)" onclick="InsertTime(wavesurfer, new_comment);">Insert Current Timecode</a>
        <p>
          <%= f.submit "Save", :class => "button" %>
        </p>
      <% end %>

      <%= link_to 'Back', url_for( :controller => 'grouptasks', :action => 'show', :id => @rec.task, :show_comments_for => @rec.id ), :class => "button secondary" %>
    </div>
  </div>
</div>

app/views/comments/show.html.erb
<%= link_to 'Edit', edit_comment_path(@comment) %> |
<%= link_to 'Back', comments_path %>