config/routes.rb
Rails.application.routes.draw do
  
  resources :permissions, :comments, :grouptasks, :statistics
  
  match 'logins/user_auth' => 'logins#user_auth', :as => 'user_auth', via: [:get, :post]
  match 'logins/logout' => 'logins#logout', :as => 'logout', via: [:get, :post]
          
  get ':controller/:action/:id'
  get ':controller/:action/:id.:format'
  

  root 'logins#index'

  post 'grouptasks/create_comment/:id'        => 'grouptasks#create_comment'
  post 'grouptasks/create_comment_reply/:id'  => 'grouptasks#create_comment_reply'
  post 'grouptasks/edit_comment/:id'          => 'grouptasks#edit_comment'
  post 'grouptasks/update_comment/:id'        => 'grouptasks#update_comment'
  

end

app/models/permission.rb
class Permission < ActiveRecord::Base
  belongs_to    :grouptask
  
  ENTRY_VALUES = ['none','self','group']
  
  def isselfviewable
    if self.viewable == 'self' || self.viewable == 'group'
      return true
    else
      return false
    end
  end
  
  def isgroupviewable
    if self.viewable == 'group'
      return true
    else
      return false
    end
  end
  
  def isselfdiscussionable
    if self.discussionable == 'self' || self.discussionable == 'group'
      return true
    else
      return false
    end
  end
  
  def isgroupdiscussionable
    if self.discussionable == 'group'
      return true
    else
      return false
    end
  end
  
  def isselfdownloadable
    if self.downloadable == 'self' || self.downloadable == 'group'
      return true
    else
      return false
    end
  end
  
  def isgroupdownloadable
    if self.downloadable == 'group'
      return true
    else
      return false
    end
  end
  
end

app/controllers/permissions_controller.rb
class PermissionsController < ApplicationController
    
  # GET /permissions
  # GET /permissions.xml
  def index
    @permissions = Permission.all

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @permissions }
    end
  end

  # GET /permissions/1
  # GET /permissions/1.xml
  def show
    @permission = Permission.find(params[:id])
    @title = "Cornichon - Task Permissions"

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @permission }
    end
  end

  # GET /permissions/new
  # GET /permissions/new.xml
  def new
    @permission = Permission.new
    @permission.grouptask_id = params[:grouptask_id]

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @permission }
    end
  end

  # GET /permissions/1/edit
  def edit
    @permission = Permission.find(params[:id])
  end

  # POST /permissions
  # POST /permissions.xml
  def create
    @permission = Permission.new(permission_params(params[:permission]))

    respond_to do |format|
      if @permission.save
        format.html { redirect_to(@permission.grouptask, :notice => 'Permissions were successfully created.') }
        format.xml  { render :xml => @permission, :status => :created, :location => @permission }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @permission.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /permissions/1
  # PUT /permissions/1.xml
  def update
    @permission = Permission.find(params[:id])

    respond_to do |format|
      if @permission.update_attributes(permission_params(params))
        format.html { redirect_to(@permission.grouptask, :notice => 'Permissions were successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @permission.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /permissions/1
  # DELETE /permissions/1.xml
  def destroy
    @permission = Permission.find(params[:id])
    @permission.destroy

    respond_to do |format|
      format.html { redirect_to(permissions_url) }
      format.xml  { head :ok }
    end
  end
  
  private
  
  def permission_params(params)
    params.require(:permission).permit(:viewable, :discussionable, :downloadable, :grouptask_id)
  end
end

app/helpers/permissions_helper.rb
module PermissionsHelper
  def new_or_edit_permission_path(permission, grouptask)
    permission ? edit_permission_path(permission) : new_permission_path(:grouptask_id => grouptask)
  end
end

app/views/permissions/_instructions.html.erb
<div id="perm_instructions">
  <p>Setting these values will determine the level of access students have to recordings, comments, and the audio files.</p>
  <p>A setting of "none" will not allow anyone except the instructor and a site admin to have that privilege within this task.</p>
  <p>A setting of "self" will only allow the owner of the recording to have that privilege within this task.</p>
  <p>A setting of "group" will allow the owner as well as all other classmates to have that privilege within this task.</p>
</div>

app/views/permissions/edit.html.erb
<div class="medium-12 medium-centered large-8 large-centered columns">
  <h1>Edit Permissions</h1>
  <div class="content_container">
    <div class="permissions_form">
      <%= form_for(@permission) do |f| %>
        <%= f.error_messages %>
        
        <%= render :partial => 'instructions' %>

        <table id ="task-permissions-settings">
          <tr>
            <td class="field_title"><h3>View Privileges</h3></td>
            <td><%= f.select :viewable, Permission::ENTRY_VALUES %></td>
          </tr>
          <tr>
            <td class="field_title"><h3>Discussion/Commenting Privileges</h3></td>
            <td><%= f.select :discussionable, Permission::ENTRY_VALUES %></td>
          </tr>
          <tr>
            <td class="field_title"><h3>Downloading Privileges</h3></td>
            <td><%= f.select :downloadable, Permission::ENTRY_VALUES %></td>
          </tr>
          <tr>
            <td><%= link_to '&#8592; Back'.html_safe, url_for(:controller => 'grouptasks', :action => 'show', :id => @permission.grouptask), :class => 'button secondary' %></td>
            <td><%= f.submit 'Save', :class => 'button' %></td>
          </tr>
        </table>
      <% end %>
    </div>
  </div>
</div>

app/views/permissions/index.html.erb
<h1>Listing permissions</h1>

<table>
  <tr>
    <th>Isselfviewable</th>
    <th>Isselfdiscussionable</th>
    <th>Isselfdownloadable</th>
    <th>Isgroupviewable</th>
    <th>Isgroupdiscussionable</th>
    <th>Isgroupdownloadable</th>
  </tr>

<% @permissions.each do |permission| %>
  <tr>
    <td><%=h permission.isselfviewable %></td>
    <td><%=h permission.isselfdiscussionable %></td>
    <td><%=h permission.isselfdownloadable %></td>
    <td><%=h permission.isgroupviewable %></td>
    <td><%=h permission.isgroupdiscussionable %></td>
    <td><%=h permission.isgroupdownloadable %></td>
    <td><%= link_to 'Show', permission %></td>
    <td><%= link_to 'Edit', edit_permission_path(permission) %></td>
    <td><%= link_to 'Destroy', permission, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New permission', new_permission_path %>

app/views/permissions/new.html.erb
<div id="content">
  <h1>Edit Permissions</h1>
  <div class="content_container">
    <div class="permissions_form">
      <% form_for(@permission) do |f| %>
        <%= f.error_messages %>
        
        <%= render :partial => 'instructions' %>

        <%= f.hidden_field :grouptask_id %>
        <table>
          <tr>
            <td class="field_title"><h3>View Privileges</h3></td>
            <td><%= f.select :viewable, Permission::ENTRY_VALUES %></td>
          </tr>
          <tr>
            <td class="field_title"><h3>Discussion/Commenting Privileges</h3></td>
            <td><%= f.select :discussionable, Permission::ENTRY_VALUES %></td>
          </tr>
          <tr>
            <td class="field_title"><h3>Downloading Privileges</h3></td>
            <td><%= f.select :downloadable, Permission::ENTRY_VALUES %></td>
          </tr>
          <tr>
            <td></td>
            <td><%= f.submit 'Save' %></td>
          </tr>
        </table>
      <% end %>
  
      <%= link_to 'Back', url_for(:controller => 'grouptasks', :action => 'show', :id => @permission.grouptask) %>
    </div>
  </div>
</div>

app/views/permissions/show.html.erb
<p>
  <b>Isselfviewable:</b>
  <%=h @permission.isselfviewable %>
</p>

<p>
  <b>Isselfdiscussionable:</b>
  <%=h @permission.isselfdiscussionable %>
</p>

<p>
  <b>Isselfdownloadable:</b>
  <%=h @permission.isselfdownloadable %>
</p>

<p>
  <b>Isgroupviewable:</b>
  <%=h @permission.isgroupviewable %>
</p>

<p>
  <b>Isgroupdiscussionable:</b>
  <%=h @permission.isgroupdiscussionable %>
</p>

<p>
  <b>Isgroupdownloadable:</b>
  <%=h @permission.isgroupdownloadable %>
</p>


<%= link_to 'Edit', edit_permission_path(@permission) %> |
<%= link_to 'Back', permissions_path %>